// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctdyoxrysdvscbzczznv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZHlveHJ5c2R2c2NiemN6em52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzIwODYsImV4cCI6MjA3MjI0ODA4Nn0.x8X-3EFquK6U3N8BJVGPse9W0sAifo6plxLJs32AZYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});